### ISSUE TITLE
Support route groups

### ISSUE THREAD

**Issue by stefanosandes** [diericx/svelte-breadcrumbs#10]
Hello,

I have an application that uses route groups, and the breadcrumb is rendering the previous segment instead of the current.

So, a route like `(authed)/inbox` that exports a `pageTitle` on its page just renders `Inbox` as a segment because the URL has a length of 1, but the route has a path length of 2.

So, this code:
https://github.com/diericx/svelte-breadcrumbs/blob/641c3b0973882500de593989bb715c5d2495d38b/src/lib/components/Breadcrumbs.svelte#L53-L54

Will result in:
routes: `['(authed)' , 'inbox']`
paths: `['inbox']`

And this:
https://github.com/diericx/svelte-breadcrumbs/blob/641c3b0973882500de593989bb715c5d2495d38b/src/lib/components/Breadcrumbs.svelte#L59-L60

Will result in:
routes: `(authed)`
paths: `inbox`

Because of this, this code:
https://github.com/diericx/svelte-breadcrumbs/blob/641c3b0973882500de593989bb715c5d2495d38b/src/lib/components/Breadcrumbs.svelte#L66

Will not include `/inbox` as part of the segment, and this segment will not be found by  ``routeModules[`${completeRoute}+page.svelte`]``.

I could solve this by making the group segment as part of the subsequent path, like this:
paths: `['(authed)/inbox']` instead of `['(authed)', 'inbox']`.

My solution was to change this:
https://github.com/diericx/svelte-breadcrumbs/blob/641c3b0973882500de593989bb715c5d2495d38b/src/lib/components/Breadcrumbs.svelte#L53
To this:
```ts
const routes = routeId.split(/(?<!\))\//).filter((p) => p != '');
```

I haven't heavily tested this, so I don't know if it can break other more complex or exotic use cases, but it works well for me.

**Comment by diericx** [comment]
Sorry for the late reply on this! I implemented the change and added some tests. This looks good to me, thank you for calling this out in such great detail!!
