### ISSUE TITLE
Only add crumb if route has a +page.svelte

### ISSUE THREAD

**Issue by brennerm** [diericx/svelte-breadcrumbs#15]
Hey :)

first things first, thanks for building this! :pray: It makes creating a breadcrumb navigation for Sveltekit apps a breeze!

The only thing that bugs me a bit is that the default crumbs function generates crumbs for all route parts, even for ones that do not have a +page.svelte. Let me explain the issue with an example.

Let's pretend we have the following folder structure
```
/src/routes
└── zones
    └── [id]
        ├── +page.svelte
        ├── +page.ts
        └── records
            └── [id]
                ├── +page.svelte
                └── +page.ts
```

Currently this will result in the following crumbs:
![image](https://github.com/user-attachments/assets/6ec8de4b-059e-45c3-807e-a7508974abb0)

Now the Zones link will point to `/zones` and the Records link will point to `/zones/[id]/records`. In this case these routes do not have a +page.svelte thus will result in a 404.

I'm aware that I could fix this by using a structure like `/[zoneId]/[routeId]` but that removes any kind of logical structure from the URL.

Maybe this is just a me problem, so feel free to simply close this issue. But I can't come up with any case where showing a link for a page that will always result in a 404 would make sense.

IMO the crumbs function could be either adjusted to not add the crumbs at all or at least don't set the URL field. This way you can keep the same structure but don't present the user any links that will lead them to a 404 page.

Let me know what you think and if you agree with this I'm happy to help with the implementation.

**Comment by diericx** [comment]
Hows this? 
https://github.com/diericx/svelte-breadcrumbs/pull/16

**Comment by brennerm** [comment]
Left a small note at the MR but other than that it looks perfect!

**Comment by brennerm** [comment]
Huge thanks @diericx!

Have a fun and safe New Year's celebration. :)

Looking forward to a new release with this feature next year. ;)

**Comment by diericx** [comment]
Thanks for reminding me! 2.0.1 is live on npm now :) Happy new year to you too!
