### ISSUE TITLE
pageData type is (not) optional

### ISSUE THREAD

**Issue by basaran** [diericx/svelte-breadcrumbs#2]
Hello,

LSP is giving me squiggly lines for `pageData`:

```
Property 'pageData' is missing in type '{ url: URL; routeId: string | null; }' but required in type '{ relPathToRoutes?: string | undefined; routeId: string | null; url: URL; crumbs?: Crumb[] | undefined; titleSanitizer?: ((title: string) => string) | undefined; routeModules?: Record<string, ModuleData> | undefined; pageData: any; }'. ​ts(2741)
```

Generated type file is like this:
```js
declare const __propDef: {
	props: {
		relPathToRoutes?: string | undefined;
		routeId: string | null;
		url: URL;
		crumbs?: Crumb[] | undefined;
		titleSanitizer?: ((title: string) => string) | undefined;
		routeModules?: Record<string, ModuleData> | undefined;
		pageData: any;
	};
	events: {
		[evt: string]: CustomEvent<any>;
	};
	slots: {
		default: {
			crumbs: Crumb[];
			routeModules: Record<string, ModuleData> | undefined;
		};
	};
};
```

We probably need this in the svelte component:

```
export let pageData: any | undefined = undefined;
```

I can send a PR if you like.

**Comment by diericx** [comment]
Hm, what is your use case? This was intentional as `pageData` pass through is required for full functionality.

**Comment by basaran** [comment]
I was simply testing the extension using the documentation provided snippet, and it would show the LSP warning. Please see below:

![image](https://github.com/diericx/svelte-breadcrumbs/assets/30809170/85aa36d6-5d53-4e53-851d-e311b939b20a)

Is there anything else I should be importing/declaring somewhere else besides the +layout ?

**Comment by diericx** [comment]
Ah I see the Readme docs got left behind. I'll update now. Try this:
```svelte
<Breadcrumbs
  url={$page.url}
  routeId={$page.route.id}
  pageData={$page.data}
  let:crumbs
>
```

Probably don't need `routeModules` either

**Comment by diericx** [comment]
The files in the `src/routes/` directory are a better reference because they actually get tested and linted, sorry :( that is definitely an issue

**Comment by basaran** [comment]
Thank you, I wanted to test this, but after restarting the pnpm dev, I am seeing another issue:

![image](https://github.com/diericx/svelte-breadcrumbs/assets/30809170/9c030697-8f15-4c62-b7c7-af0c3558dd71)

Have you tested the extension with typescript and postcss? Let me try to remove the scss in the page.svelte and debug further.

**Comment by diericx** [comment]
That looks unrelated to this plugin.

**Comment by basaran** [comment]
So, If I keep a:

```
<style lang="scss">
..
</style>
```

in the +layout.svelte, and the Breadcrumbs tag in the +layout.svelte, the dev server complains as postcss issue for the typescript block in the +page.svelte. I will debug further.

**Comment by basaran** [comment]
I have this in the dev-tools:

![image](https://github.com/diericx/svelte-breadcrumbs/assets/30809170/5885106e-dcb0-4d18-aaa6-23f217557aec)

and this is line 18:

```js
import "/node_modules/.vite/deps/svelte_internal_disclose-version.js?v=31be23b5";
```

**Comment by basaran** [comment]
So, this is what I have in the devtools:

![image](https://github.com/diericx/svelte-breadcrumbs/assets/30809170/e94bc6bc-20c8-4392-b6a0-4c1d406f94d8)

It also complains about the titleSanitizer not being passed. So, what I will do, I will create a new stock sveltekit project on the @latest and test it there.

**Comment by diericx** [comment]
Oh interesting. The library is trying to load all of the svelte modules here: 
https://github.com/diericx/svelte-breadcrumbs/blob/55945342d2d39cf75908405da188648b95625302/src/lib/components/Breadcrumbs.svelte#L24

That error reads to me like this line failed `import.meta.glob("/src/routes/**/*.svelte")`, like it was able to find the path to a file but was unable to actually load them in?

I wonder if this has something to do with SSR. Maybe something goes wrong if this code is running on the client only?

**Comment by basaran** [comment]
Nevermind the missing sanitizer issue, pnpm was pulling a cached breadcrumbs.svelte (which I had edited within node_modules because I'm lazy).

So, I cleaned up the store in this project and ensured I have a stock npmjs svelte-breadcrumbs. The postcss issue remained with the snippet you provided, but this one worked (without the routeId you had):

```
                <Breadcrumbs
                    url={$page.url}
                    pageData={$page.data}
                    let:crumbs>
                    <div>
                        <span><a href="/">Home</a></span>
                        {#each crumbs as c}
                            <span>/</span>
                            <span>
                                <a href={c.url}>
                                    {c.title}
                                </a>
                            </span>
                        {/each}
                    </div>
                </Breadcrumbs>
```

although, LSP would complain on the missing routeId... But it did work.

Then I tried to use and see if I can  pass a titleSanitizer function. I got back the postcss error again. I will let you know once I try a stock sveltekit. It would be easier to debug this then.

P.S I checked the src routes, and it's clean with only +page.svelte:

![image](https://github.com/diericx/svelte-breadcrumbs/assets/30809170/c44926e2-2a67-47b0-aa74-93ab047fbb34)

**Comment by basaran** [comment]
Do you think those nested folders inside the /about might be causing the issue ?

**Comment by diericx** [comment]
What version of Svelte and Sveltekit? Is there a public repo anywhere reproducing this? 

I don't think it is nested folders as I have that running locally.

**Comment by basaran** [comment]
I will make a clean repository and try to reproduce the error there in the next few hours.

**Comment by diericx** [comment]
I believe #4 and #5 have fixed the HMR issues

**Comment by diericx** [comment]
I've actually reverted that change as it was breaking the functionality. It looks like I can't reproduce this issue in the breadcrumbs repo anymore but can't seem to figure out what is causing it in larger repos either... HMR still broken in my app as well

**Comment by basaran** [comment]
Thank you for the update. I am still using my fork without any issues. I am hoping this weekend I will have some time to test the changes you mention.

**Comment by basaran** [comment]
~~Hello, the breadcrumb test repo and the actual app I'm working on appears to be fine. Perhaps sveltekit got updated or something and that fixed the "issue". Is everything okay on your end as well or are you having any issues?~~

I take it back, it's still having issues. It just took a few saves, and reloads.

**Comment by diericx** [comment]
Sorry, didn't see that edit. As it seems directly related to the glob import line it might be best to raise this to Svelte or Vite. I'll try to get something written up today.

**Comment by diericx** [comment]
@basaran can you try updating to `1.2.5` and clearing site data (in Firefox it is "Clear Cookies and Site Data") to ensure no older version is cached in the browser and try again? It seems to be working for me.

**Comment by basaran** [comment]
I think it is fine now. I didn't encounter any issues with the test project. Thank you for all your work. Closing.
