### ISSUE TITLE
Possible Vite 4.0.0 dependency issue?

### ISSUE THREAD

**Issue by nickludlam** [diericx/svelte-breadcrumbs#8]
Hey so when I'm running updates, I get this warning about unmet dependencies:

```
Already up to date
Progress: resolved 672, reused 538, downloaded 0, added 0, done
 WARN  Issues with peer dependencies found
.
└─┬ svelte-breadcrumbs 1.2.5
  └─┬ @sveltejs/kit 1.30.4
    ├── ✕ unmet peer vite@^4.0.0: found 5.1.4
    └─┬ @sveltejs/vite-plugin-svelte 2.5.3
      ├── ✕ unmet peer vite@^4.0.0: found 5.1.4
      └─┬ @sveltejs/vite-plugin-svelte-inspector 1.0.4
        └── ✕ unmet peer vite@^4.0.0: found 5.1.4

Done in 8.4s
```

I'm still new to node and typescript so my apologies if I'm misattributing this warning, but doesn't this stem from this section in the package.json ?

```
      "dependencies": {
        "@sveltejs/kit": "^1.24.0"
      },
```

From what I've read, the `^` operator allows for minor version bumps, but not major ones. So now sveltekit 2 is out, this is now technically unmet?

**Comment by diericx** [comment]
I recently updated Vite in this repo and this is what my `package.json` looks like for `vite` and many other packages:

```
"vite": "^4.4.2"
```

Which translates to:

```
>=4.4.2 <4.5.0
```

That is a mistake, thanks for pointing this out. I am so used to using that syntax in my projects, I didn't realize how problematic it could be in a library. I'll update those to remove any semver specificity and it should fix it up for you.

Try out `1.2.6` now

**Comment by nickludlam** [comment]
Hmm, I still seem to get the warning:

```
Progress: resolved 672, reused 538, downloaded 0, added 0, done
node_modules/.pnpm/@sveltejs+kit@1.24.0_svelte@4.2.12_vite@5.1.5/node_modules/@sveltejs/kit: Running postinstall script, done in 432ms

dependencies:
+ svelte-breadcrumbs 1.2.6

 WARN  Issues with peer dependencies found
.
└─┬ svelte-breadcrumbs 1.2.6
  └─┬ @sveltejs/kit 1.24.0
    ├── ✕ unmet peer vite@^4.0.0: found 5.1.5
    └─┬ @sveltejs/vite-plugin-svelte 2.5.3
      ├── ✕ unmet peer vite@^4.0.0: found 5.1.5
      └─┬ @sveltejs/vite-plugin-svelte-inspector 1.0.4
        └── ✕ unmet peer vite@^4.0.0: found 5.1.5

Done in 3s
```

**Comment by diericx** [comment]
in #9 I moved `@sveltejs/kit` to `devDependencies`. Hopefully that fixes the issue for you!

**Comment by nickludlam** [comment]
Yes that's fixed it! Thanks so much for all the effort @diericx
